export enum actionTypes {
    // ORDER FORM CPT
    SET_LOADING = "SET_LOADING",
    SET_ORDER_FORM_DATA = "SET_ORDER_FORM_DATA",
    FETCH_ORDER_FORMS = "FETCH_ORDER_FORMS",
    FETCH_ORDER_FORM = "FETCH_ORDER_FORM",
    ADD_NEW_ORDER_FORM = "ADD_NEW_ORDER_FORM",
    EDIT_ORDER_FORM = "EDIT_ORDER_FORM",
    DELETE_ORDER_FORM = "DELETE_ORDER_FORM",
    SET_PAGE = "SET_PAGE",
    GET_ORDER_FORM_SETTINGS = "GET_ORDER_FORM_SETTINGS",
    SET_ORDER_FORM_SETTINGS = "SET_ORDER_FORM_SETTINGS",

    // STYLING
    SET_SHOW_STYLING = "SET_SHOW_STYLING",
    SET_STYLES = "SET_STYLES",

    // PRODUCTS
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    SET_PRODUCTS = "SET_PRODUCTS",

    // DRAG AND DROP
    SET_DND_DATA = "SET_DND_DATA",
    GET_DND_DEFAULT_DATA = "GET_DND_DEFAULT_DATA"
}